### ISSUE TITLE
change header and footer in print 

### ISSUE THREAD

**Issue by avniraiyani** [MatthewHerbst/react-to-print#110]
I want to set header and footer in all pages like company logo on header and some details in footer

**Comment by MatthewHerbst** [comment]
Header and footer are controlled by the browser print dialog, it's not something we set. The header is normally the date and page title, and the footer is normally the page url and the page number. If you mean you just want to add some React components above/below the thing being printed, just wrap the thing being printed with those elements before the print is triggered.

**Comment by mayurdere** [comment]
To remove header and footer
@media print {
  h4.class-name
  @page{
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 0px;
    margin-bottom: 0px;
    }
}
To change the header text and PDF File name
componentDidMount() {
        document.title = 'My Candidate Profile'; //PDF File Name
    }

[http://cuttingchai.info](url)

**Comment by vipul3936** [comment]
I am having the same issue as @avni-logistic . please help if you have any solution for it

**Comment by thebinarybrain** [comment]
please help i am also having same issue as @avni-logistic

**Comment by MatthewHerbst** [comment]
Hi @thebinarybrain as mentioned above, the only option you have is to add/remove content to the page before/after print. You can use the `onBeforeGetContent` prop to do this, or you can hide/show elements using CSS with the `@media print { ... }` query. There is no print API that browsers expose to allow settings headers/footers unfortunately.

**Comment by gudapraveenkumar** [comment]
Any update on having a header and footer on each page? And why this issue is closed without providing a solution? Or I'm I missing something

**Comment by MatthewHerbst** [comment]
> Any update on having a header and footer on each page? And why this issue is closed without providing a solution? Or I'm I missing something

The issue is closed because adding a header/footer is not something you need this library for. You can _kind of_ control this on your own with your components and using [CSS paged media](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_paged_media). However, there is no generally available solution to the problem at this time. This library has no knowledge of how many pages your component will take to print. All we do is extract your component out of the larger React DOM tree and send it to be printed. Once the browser dialog box opens we lose all control.

- [A StackOverflow post about this topic](https://stackoverflow.com/questions/1360869/how-to-use-html-to-print-header-and-footer-on-every-printed-page-of-a-document)
- [A blog post you may find helpful](https://www.geeksforgeeks.org/how-to-print-header-and-footer-on-every-printed-page-of-a-document-in-css/#)
- [Another blog post](https://estart.hr/en/news/19/HTML--CSS:-Create-header-and-footer-on-the-top-and-bottom-of-every-printed-page/)

**Comment by alekseykurylev** [comment]
@MatthewHerbst, How can I output multiple components in "content". For example, in the first the logo, and in the second the main content?
