### ISSUE TITLE
Cancel printing events

### ISSUE THREAD

**Issue by smallWanziOf** [MatthewHerbst/react-to-print#112]
How to determine whether a value exists before printing, and then block printing events

**Comment by MatthewHerbst** [comment]
Don't fire the trigger when you detect that the value doesn't exist? We don't know anything about your code, only you can check if a value exists or not. This sounds like a question that might be better places on StackOverflow.

**Comment by Si3rr4wow** [comment]
I know this is closed but I hope it's ok to throw in my 2 cents here because this tread kept coming up while I was googling for something like this.

I had a scenario where I needed users to provide authorisation before printing, and prevent that print if the auth failed or was cancelled.

I achieved this by awaiting a promise in onBeforePrint. The promise passes it's resolve and reject functions up through a handler function I passed into an abstracted ReactToPrint component. I looks something like this

_print-trigger.jsx_
```
import React, { useMemo } from 'react';
import ReactToPrint from 'react-to-print';

const PrintTrigger = props => {
  const content = useMemo(() => {
    const p = document.createElement('p');
    const t = document.createTextNode('text that will be printed if promise resolves');
    h.appendChild(t);
    return h;
  }, []);

  return (
    <ReactToPrint
      trigger={props.render}
      content={() => content}
      onBeforePrint={async () => {
        await new Promise((resolve, reject) => {
          props.clickHandler(resolve, reject);
        })
      }} />
  );
};

export default PrintTrigger;
```
_print-button-holder.jsx_
```
import React from 'react';

import PrintTrigger from './print-trigger';

const PrintButtonHolder = props => {
  const handlePrintingClick = (resolve, reject) => {
    if(props.userCanPrint) {
      resolve();
      return;
    } 
    reject()    
  }

  return (
    <div>
      <p>Press the button below to check if you&apos;re authed and then print if you are</p>
      <PrintTrigger
        clickHandler={handlePrintingClick}
        render={() => (
          <button>
            Click me to try to print
          </button>
        )} />
    </div>
  );
};

import withAuthOverlay from '/imports/utils/with-auth-overlay';
// withAuthOverlay provides a boolean prop to PrintButtonHolder called userCanPrint 
export default withAuthOverlay('user_can_print')(PrintButtonHolder) 
```

Here I'm checking data provided to react to print's parent by a HOC and using this to determine whether or not to print but you could use the same paradigm to make an api call or whatever you need.

I've not handled the rejection in any way, the print just doesn't happen if the promise is rejected. I've not tested this but I'd imagine that if you want to handle an error here you could do this with the onPrintError prop for ReactToPrint.

Hope that helps anyone else who stumbles on this thread like I did.

**Comment by MatthewHerbst** [comment]
Thanks for the example @Si3rr4wow
