### ISSUE TITLE
How to print Stateless components with React to Print?

### ISSUE THREAD

**Issue by nitingupta220** [MatthewHerbst/react-to-print#191]
I'm trying to print a stateless component/ functional component with React to print but the function is doing nothing and throwing error in console that it will only work with class components.
Is their any way around to print functional components/stateless components?
Please reply fast.
@MatthewHerbst

**Comment by MatthewHerbst** [comment]
Hello. There is no way to use functional component right now as the content since it would require the library changing it's React peer dependency to ^16.3, which would be a breaking change. We will do that eventually, but, as far as I know, there is no reason why someone can't use a class component instead of a functional component. If there is something you are doing with a functional component that you cannot do with a class component, please let me know.
