### ISSUE TITLE
How to set default paper size ?

### ISSUE THREAD

**Issue by leanesanity** [MatthewHerbst/react-to-print#253]
Good Day,

Can you help me ?
Since there is not really much information about setting defaults for printing for this library.
I would like to ask if it's possible to set in this library? 
Would appreciate if you could provide sample on setting default paper sizer and other options,

Thank you very much

**Comment by MatthewHerbst** [comment]
Hello. The default paper size is determined by your printer and browser, and is not something this library has any control over. All we do is open the print preview modal from your browser with the specified content. We unfortunately have no ability to modify settings in that modal because there is no standard browser API to do that.
