### ISSUE TITLE
findDomNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by kevfay** [MatthewHerbst/react-to-print#261]
I am referencing a component to be printed and receiving the error below when clicking the button for the print popup:

![image](https://user-images.githubusercontent.com/26905265/84176328-35349c00-aa4f-11ea-90b6-7b3b50b18cec.png)

![image](https://user-images.githubusercontent.com/26905265/84176425-5c8b6900-aa4f-11ea-9853-59612743eb2b.png)

`<Buildsheet vin={vin} ref={componentRef} /> `
-- it's a class component

Any suggestions? Thank you.

**Comment by MatthewHerbst** [comment]
Hello. Apologies for not responding sooner. We do use `findDOMNode`. We can't change that right now since it would be a breaking change since it would force our users to use a newer version of React.

It seems the error you are getting is actually a warning, and not something that needs to be dealt with right now, unless you are seeing something not work? When React 17 comes out we will have to remove `findDOMNode` likely so we will deal with that at that time.
