### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode - When calling from functional components with useReactToPrint

### ISSUE THREAD

**Issue by mav1283** [MatthewHerbst/react-to-print#282]
I got this warning when calling from function components with useReactToPrint:

![find-dom-node](https://user-images.githubusercontent.com/11674969/91853934-8393b880-ec95-11ea-8d6b-8a56b06df923.PNG)

**Comment by MatthewHerbst** [comment]
https://github.com/gregnb/react-to-print/issues/261

Fixing this would be a breaking change for this library, and even in [React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html) they are not removing `findDOMNode`

This is a warning, not an error (they really should use `console.warn` instead of `console.error`). Is this causing you a problem, or just something you saw in the console?

**Comment by mav1283** [comment]
@MatthewHerbst  Yeah it appears in the console, should i use forwardRef here? I have this stateless class <Document ref={componentRef} /> component that just renders text data,

**Comment by MatthewHerbst** [comment]
You won't be able to fix this issue unless you turn off strict mode for the places where `react-to-print` is used, because `findDOMNode` is going to be called by us. Eventually we'll switch but it's a breaking change and since it's not really a problem (that I know of) for there to be warnings in strict mode, it doesn't seem worth making the change right now

**Comment by 2hands10fingers** [comment]
We'd definitely like this to be amended for our client as it's a crucial feature for our client. I love this library, and we rely on using StrictMode as a team.

**Comment by MatthewHerbst** [comment]
@2hands10fingers is this issue actually preventing you from using this library and/or strict mode? It's just a deprecation warning, not an error of any kind. My plan is to drop React 15 support once React 17 is released. Dropping React 15 support will enable me to easily solve this, though even in 17 this will still be a warning, not an error

**Comment by MatthewHerbst** [comment]
If this is actually breaking something in strict mode right now I'm happy to look into fixing it now, but I've been under the impression that it is just a warning, and nothing breaks from it

**Comment by yusuf-saydullayev** [comment]
Hi, Has any updates to remove findDOMNode. In react [18.3](https://github.com/facebook/react/releases/tag/v18.3.0) adds warnings for deprecate this API  and in v19 will be removed.

thanks.
