### ISSUE TITLE
Custom pagination on printed pages required

### ISSUE THREAD

**Issue by Shubham-luv2code** [MatthewHerbst/react-to-print#306]
Using this module and wanted to know how to put custom pagination in the react-to-print module. Quick leads would be appreciated. Thanks!

**Comment by MatthewHerbst** [comment]
Hi there. I'm not sure I understand what you are trying to do? What are you trying to paginate? This library only does printing, so if you want to paginate it needs to happen before printing is done. You can use the `onBeforeGetContent` method to change the page content before the print if you need to

**Comment by Shubham-luv2code** [comment]
Basically I need to paginate at the footer section the number of pages getting printed e.g. 1/5 then second page goes like 2/5. So just wanted to know How we'll get to know that an A4 page by default has reached to end and we show footer.
I'll try onBeforeGetContent. If you've a suggestion to do.Please let me know

**Comment by MatthewHerbst** [comment]
Ah, I think I understand. You want to specify where the page numbers show up instead of using the default option that the user's browser/printer provides. Unfortunately once we call `.print()` internally we lose all control. There is no standard printing API to control the settings of the Print Preview window, so we have no ability to set/change any of the settings in there. My guess is you can achieve what you want using some CSS such as `@media print` and `@page`. For example: https://stackoverflow.com/questions/16649943/css-to-set-a4-paper-size
