### ISSUE TITLE
not showing content in electron

### ISSUE THREAD

**Issue by rujsga** [MatthewHerbst/react-to-print#32]

**Comment by gregnb** [comment]
Can you paste some screenshots? Maybe a link to an example app?

**Comment by rujsga** [comment]
This is react png works fine but in electron content is not displaying.
![react](https://user-images.githubusercontent.com/40892723/42407198-55f26dfe-81d5-11e8-9668-78a3a83d831b.png)

 I am attaching the electron screenshot.
![electron](https://user-images.githubusercontent.com/40892723/42407235-9c7f5dcc-81d5-11e8-8c05-be40a56b9eae.png)

**Comment by gregnb** [comment]
Try the new beta version which is going to rely on an iframe to solve the cross origin issues some people are experiencing.

```
npm install react-to-print@2.0.0-beta-3
```

and let me know the feedback if this solves issues

**Comment by gregnb** [comment]
@rujsga Can you update me if that worked?

**Comment by konstantinkreft** [comment]
@rujsga Try to use chrome's `window.open()` implementation for electron. Worked fine for me with electron and `nativeWindowOpen: true`.

With the default electron `window.open()` implementation you are not able to update the `document` of the created window. But since the `window.print()` API is available you are able to see the print dialog without any content.

Here you can find out more about chrome's `window.open()` implementation: https://github.com/electron/electron/blob/master/docs/api/window-open.md#using-chromes-windowopen-implementation

As @gregnb mentioned you should also be able to use new iframe beta version. Tested with electron and worked for me.

**Comment by gregnb** [comment]
Great news this is the positive feedback I was hoping for so if there is continued feedback I will merge this into master

**Comment by gregnb** [comment]
I believe the issue has been solved and you can upgrade 

```
npm install react-to-print@2.0.0-alpha-1 --save
```

**Comment by rujsga** [comment]
Hey, Sorry for not replying earlier. My Issue has been solved by 
npm install react-to-print@2.0.0-alpha-1 --save.

Thank you for solving my issue.
@gregnb
