### ISSUE TITLE
Custom Fonts Not loading in Reactjs

### ISSUE THREAD

**Issue by jenridunn** [MatthewHerbst/react-to-print#338]
I've been testing this issue in your code sandbox changing only this part of your code:

```        <ReactToPrint
          trigger={() => <a href="#">Print this out now!</a>}
          content={() => this.componentRef}
          fonts={[
            {
              family: "Gilroy Black",
              source:
                "url(https://s166.convertio.me/p/ZnLj6w7hk5UMWX-0FIuwBg/9d87d9f4c362f9626dd4e1ce212104a7/Gilroy-Black-_1_.ttf)"
            }
          ]}
        />
```

When I click "print this out" the font remains the same. I've been trying also with woff files and cdn links like this: 
url('http://fonts.cdnfonts.com/css/sf-hallucination-2') *using single quotes inside the url(...)

And the font remains unchanged. What am I doing wrong?  Thanks!

**Comment by MatthewHerbst** [comment]
I am able to reproduce. Investigating, thanks for reporting

**Comment by MatthewHerbst** [comment]
Hi @jenridunn apologies for taking so long on this, it's been tricky to figure out. So, the `fonts` prop was originally added due to a bug report in #281. Taking a closer look at that issue, it seems it may have been a Chrome-specific bug that may have since been fixed. I have updated the example for `react-to-print` on [codesandbox](https://codesandbox.io/s/rzdhd) to use an imported font and it seems to work without using the `fonts` prop at all. It's harder to show a local font on there, but I ran the library's local examples with local and imported fonts (again, without using the `fonts` prop) and everything seems to be fine.

Could you please verify that for me? If that's all true it may make sense to deprecate the `fonts` prop since I don't think there is a use case for it any longer

**Comment by jenridunn** [comment]
Hi @MatthewHerbst ! Exactly as you stated, the prop "fonts" should be deprecated. With the last update, if you want to change the font you have to include the class that makes reference to the font-face you want to display. It's so much better this way. Thank you so much Matthew. The issue is now solved.
