### ISSUE TITLE
Safari print action doesn't hide itself on render

### ISSUE THREAD

**Issue by davedbase** [MatthewHerbst/react-to-print#340]
I'm having an issue on mobile Safari that's proving to be a bit cumbersome to track down. Here is a video of the issue in action: https://www.loom.com/share/eac34e5f9d6342ec98d3e996d738f9e1

To see the issue directly in Safari visit: https://www.ethanallen.com/on/demandware.store/Sites-ethanallen-us-Site/en_US/RomaV2-Start?locale=en_US&start_item=1130516 (click a size option ie small > click Next: Additional options > click Continue > click Print details > close the print action without printing > click Share).

Upon clicking share you'll notice that the printed component is rendered on the full page. This only happens on Safari and every other browser seems stable. Here's how we're structuring the component:

```jsx
// Component that generates the component reference
const reactToPrintContent = useCallback(() => printComponentRef.current, []);

// Handles the action of printing the page
const handlePrint = useReactToPrint({
  content: reactToPrintContent,
  onBeforePrint: () => printItem(api_path, token, item.id!),
  onAfterPrint: () => trackEvent("printed"),
});
```

Then the component itself is referenced like so (the component contains all the print view details which are rendered full screen after clicking share):

```jsx
<PrintableItem
  locale={locale}
  item={item}
  ref={printComponentRef}
/>
```
PrintableItem starts looks similar to the following:
```jsx
  render() {
    return (
      <PrintableItemStyle>
        <LocalisationContext.Consumer>
          {(lang) => (
            <></>
           )}
       </LocalisationContext.Consumer>
     </PrintableItemStyle>
   )
}
```
I'm wondering if this could be an issue where the reference is located. It's also curious that this happens when you click Share. The share action is simply using setState() to load our modal Share component.

Any guidance on this would be appreciated.

**Comment by MatthewHerbst** [comment]
Hi there. Thanks for the detailed report. It's really cool to see the library being used on such a major website.

I'm looking into the issue now. My initial guess is that it has something to do with newer versions of Safari not always treating [`Window.print`](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) as blocking.

Can you please try setting the `removeAfterPrint` prop on `useReactToPrint` to `true`? That should force removal of the print iframe after the print dialog closes. Internally we call a `handleRemoveIframe` method after printing, though the logic in that method doesn't remove the iframe by default. (This is a legacy issue from when I started maintaining the code, and making it the default would be a breaking change to the library. I plan on releasing a new major version in a month or two that fixes this along with many other legacy issues.)

Note: I'm slightly concerned that bad things could happen if you try to remove the iframe while the print dialog is still open (which could happen if Safari doesn't block on `Window.print`) but I _think_ it might be ok, since the print dialog would have gathered the info it needs by then (from my experience, the browsers convert the HTML to a PDF and what you see in the print dialog is a PDF rendering of the content, so losing access to the original print iframe _shouldn't_ be an issue to the best of my knowledge).

https://github.com/gregnb/react-to-print/blob/47adbf8ce9df1d07fce44ea940e34355ea2eb53e/src/index.tsx#L420-L432

Please let me know if that helps

**Comment by davedbase** [comment]
Thanks for the really fast response! This app is actually part of a larger product called Framezee. It's an embeddable library that a few major brands are using. It solved a problem nicely for us, so kudos for the good work!

I added removeAfterPrint as a property with true inside the useReactToPrint object and nothing changed unfortunately. The weirder part is that it ONLY displays when another state value is modified.

Your help on this is really appreciated =)

**Comment by MatthewHerbst** [comment]
> The weirder part is that it ONLY displays when another state value is modified.

Very strange. I'll play around with it a bit and get back to you in a couple hours.

**Comment by MatthewHerbst** [comment]
Can you tell me more about what your `printItem` method does? I modified the hook example in the repo to have a button that changes state but wasn't able to replicate the issue as I see it on the ethanallen site. I'm also curious how `printComponentRef` is defined.

The thing I'm looking at is that after the print (I can replicate the issue by cancelling or doing the print), and then clicking share, the contents of the `body` is actually replaced by the contents of the print iframe. So it's not that the print iframe is suddenly displaying when it shouldn't be, but the actual content of the page has changed, which is not something this library would be doing in any way. You can see when inspecting the page, the print iframe (`id='printWindow'`) is located at the bottom of the page content, below the hidden `__privateStripeMetricsController0770` iframe.

After printing then sharing, the structure of the page is:

```html
<html>
  <head>...</head>
  <body>
    <script>...</script>
    <div id="framer">
      <script>...</script>
      <div class="sc-bYEvPH btsZaj">
        <style>...</style>
        <div class="sc-jSgupP fStLsH">...</div>
        <div class="body">
          <div class="sc-iwyYcG cunCrG full">
            <div class="sc-bBXqnf jBfRzz">...</div> <!-- This is the print iframe content, react-to-print cannot have done this -->
            <div class="sc-dlfnbm dFmfFp full">...</div>
          </div>
        </div>
        <div class="sc-fubCfw dIsJZf">...</div>
    </div>
    <iframe name="__privateStripeMetricsController0770" />
    <iframe id="printWindow"> <!-- react-to-print inserted this iframe during printing -->
      #document
        <html>
          <head>...</head>
          <body>
            <div class="sc-bBXqnf jBfRzz">...</div> <!-- Notice the class is the same as the content above -->
          </body>
        </html>
    </iframe>
  </body>
</html>
```

**Comment by davedbase** [comment]
@MatthewHerbst I spent an hour reviewing our implementation and reading through the docs very closely. Believe it or not it was quite a silly mistake. We didn't wrap the component to print in a style: none div! I suppose we never really caught the issue or thought to read that closely because the component worked without the style none inclusion. Only until you click share (which is the only state changing action on the page) did this come up as a bug. So a mix of the component usecase and bad doc reading obfuscated the issue. I can confirm it's resolved. I can close out this issue and save you time digging further into this =) sorry!

**Comment by MatthewHerbst** [comment]
Glad you were able to figure it out! If there's anything I can do to make the docs simpler please don't hesitate to let me know
