### ISSUE TITLE
Over-riding pageStyle default strips print formatting that removes date/time

### ISSUE THREAD

**Issue by cubby-alexander** [MatthewHerbst/react-to-print#350]
I just want to add a margin to my print document, so I'm passing the default string to the pageStyle prop with a modified margin value -- everything else the same. Problem is, this strips the formatting that removes the print date/time from the top of the document, which is not an effect I want.

For ease of reference I'm pulling this from the [index](https://github.com/gregnb/react-to-print/blob/a2fd08caaac9a7f27eacf4150d25b77492327920/src/index.tsx#L29):

> "@page { size: auto;  margin: 0mm; } @media print { body { -webkit-print-color-adjust: exact; } }"

and passing this as the prop value:

> "@page { size: auto;  margin: **20**mm; } @media print { body { -webkit-print-color-adjust: exact; } }"

Any suggestions?

**Comment by MatthewHerbst** [comment]
Heh, the `margin: 0mm` is our very hacky way of removing that stuff since there is no browser API to do so unfortunately. 

I would suggest just adding a div to your print component that only has the margin during print

```jsx
const ComponentToPrint = () => {
  return (
    <div className="print-margin">
        <SomeComponent />
        <SomeOtherComponent />
    </div>
  );
};
```
In your CSS:
```css
.print-margin {
  @media print {
    display: 'block';
    margin: 20mm;
  }
}
```
I haven't run that exact code but I think it should work. Please let me knowHeh, the `margin: 0mm` is our very hacky way of removing that stuff since there is no browser API to do so unfortunately.
