### ISSUE TITLE
How can I use window.print as my trigger ?

### ISSUE THREAD

**Issue by makhesko** [MatthewHerbst/react-to-print#359]
Hi, I am currently using a custom button to trigger the print  and it is working as expected. But I also want that default print method to trigger ReactToPrint and work as same.

**Comment by MatthewHerbst** [comment]
Hi there. It's not fully possible to do what you want unfortunately. The browser controls what happens when you default print through it, and no major browser that I am aware of gives developers any way of interacting with that via JS on a webpage (it could be done via browser extension). In addition, it's possible for multiple `ReactToPrint` instances to exist on a single page (imagine having a print button for every graph on a dashboard), so even if this could be done you would have a tough time knowing which instance to send the print to.

You should be able to use the [`onbeforeprint`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint) browser event to listen for a global print call and then call `ReactToPrint`, but I'm not sure if you would be able to stop the global print event from going through.

**Comment by makhesko** [comment]
Ok, thank you for your reply. But I thought that `print` prop may be for that. I am not getting how to use the `print` prop, do you have any example for that?

**Comment by MatthewHerbst** [comment]
The `print` prop is meant to be used in non-browser environments, such as Electron. When passed, `ReactToPrint` will call that function instead of `window.print` (note that `window` doesn't refer to the global `window` of your page, but instead to a hidden `iframe` that `ReactToPrint` creates to print only the content you want printed)

**Comment by MatthewHerbst** [comment]
Working Electron example with how to print using `react-to-print` is now available! https://stackoverflow.com/questions/68751490/electron-print-iframe-given-reference-to-it
