### ISSUE TITLE
Issue with styled-components and Safari

### ISSUE THREAD

**Issue by ninosaurus** [MatthewHerbst/react-to-print#362]
Hello guys, 
We have founded an issue which is mobile Safari browser specific and here is how to reproduce it:
1. Trigger print action
2. Close print modal
3. Put the Safari in background (open another app)
4. Open Safari from background
5. Styles are not applied

Here's the [codesandbox](https://codesandbox.io/s/react-to-print-forked-v6iyc) demo where you can reproduce it. And here's the video of me reproducing it. You will notice that styles (color: red;) disappeared one Safari is opened from background.

In this video I was using iPhone 8 with iOS 14.4.2

https://user-images.githubusercontent.com/17122401/116399125-dfb0db80-a828-11eb-819d-ebea252193d2.MP4

**Comment by MatthewHerbst** [comment]
Well that's pretty strange! Thanks for reporting, and for the video and codesandbox. I'll have to find a way to test this since I don't how a iOS device myself, though maybe I can reproduce in the emulator on MacOS.

Just to be sure, can you please verify that this doesn't happen when doing a "normal" (without react-to-print) print of the page?

Will be researching this tonight. Love browser differences... 😄

**Comment by ninosaurus** [comment]
> Just to be sure, can you please verify that this doesn't happen when doing a "normal" (without react-to-print) print of the page?

Yup, it's working fine, our insane QA team found this, don't ask me how :)

> Will be researching this tonight. Love browser differences... 😄

😅  I did a little debugging and it looks like none of styles (from styled-components) exists on the page, like they are deleted or sth like that.

**Comment by MatthewHerbst** [comment]
Ok, in good news, I can replicate this on the iOS simulator on my Mac, so I can start debugging. I didn't come across anything in research last night that was an obvious answer. I do know 100% for sure `react-to-print` does not delete any styles from the page. Will ping back what I discover.

**Comment by ninosaurus** [comment]
Any updates on this issue? @MatthewHerbst

**Comment by neverbe10** [comment]
@MatthewHerbst  Any update on this issue? It's happening in safari on MacOS too

**Comment by MatthewHerbst** [comment]
Apologies, I have had to focus on work the last few months. I hope to have time this coming weekend to spend a few days working on this lib. I appreciate your patience.

**Comment by gianpieroc** [comment]
Hello!. Do we have any updates on this issue?

**Comment by axel127** [comment]
We're now running into this as well.

**Comment by MatthewHerbst** [comment]
Hi, sorry for the delayed response answering here. Can you please confirm to me the version of `react-to-print` you are using? Can you please try testing with the newest version? There was an update a couple of weeks ago that fixed some style issues, though I don't know if it fixed this one. I don't have an iPhone or an iPad so it's very difficult for me to test Mobile Safari. Please let me know if this is still an issue on the latest version, thank you

**Comment by axel127** [comment]
@MatthewHerbst - No worries, thanks for taking a look. We're on `2.14.1`. I just tested with `2.14.4` and it actually looks to be behaving better. I'll do some more testing and follow up if we continue to have issues.

Side note: I'm guessing you're not a Mac user if you don't have any iOS devices, but if you have access to a Mac the Simulator in XCode is very useful for reproducing and debugging mobile Safari issues.

**Comment by MatthewHerbst** [comment]
>  I'll do some more testing and follow up if we continue to have issues.

Please do let me know, thank you

> Side note: I'm guessing you're not a Mac user if you don't have any iOS devices, but if you have access to a Mac the Simulator in XCode is very useful for reproducing and debugging mobile Safari issues.

I am actually! I totally forgot about that as an option heh. I also find the simulator to be incredibly difficult to use sometimes since translating mouse movements into touches doesn't always work well.

Having just tested, I can confirm that the steps to reproduce create a broken experience on `react-to-print` v2.12.3 (from OP example), but the steps to reproduce create a working experience with the newest version of `react-to-print` v2.14.4. My assumption is that this change fixed it: https://github.com/gregnb/react-to-print/commit/8dee30b3dac94c54a562802229738f8d4473e63b

If you continue to encounter issues please let me know and we can re-open. Thanks for bringing this back to my attention!
