### ISSUE TITLE
Check PDF creating process

### ISSUE THREAD

**Issue by KimTrongNguyen** [MatthewHerbst/react-to-print#408]
Hello, I just tested react-to-print with a set of data (about 320 pdf pages). When I click save the output pdf file, and then close the application right after that, the file will be damaged and broken. I think it's because the file has not been written completely. So I think about making a progress bar to notify users when the writing file process has been done. But I don't know how to determine when it done, is there any way or method to call to check for this?
Or is there any way to detect when the user click Print on the dialog? (my second solution is to set a specific amount of time to the progress bar when the Print button is triggered)
Thank you so much!

**Comment by MatthewHerbst** [comment]
Hello. That would be something the browser controls unfortunately. `react-to-print` tells the browser what to print, but the browser is in full control of the actual printing process, including saving files as PDF. Unfortunately there is no current API for JavaScript to communicate with the browser about printing 😢  I am actually in the slow process of proposing an API to WC3 but knowing that process even if it was accepted it will be years before it makes it into browsers.

If possible, something you could do is to have the server generate the PDF and then download the file for the user (instead of printing it). That way you could track the download from your server with a progress bar.

**Comment by KimTrongNguyen** [comment]
@MatthewHerbst Thank you. I just edit the question and add a second solution (a little bit dirty trick but this will solve it in my case).
Is there any way to detect when the user click Print on the dialog? (my second solution is to set a specific amount of time to the progress bar when the Print button is triggered)

**Comment by MatthewHerbst** [comment]
> Is there any way to detect when the user click Print on the dialog

There is not unfortunately. Once the dialog opens we lose all control 😢
