### ISSUE TITLE
@page size not working on firefox

### ISSUE THREAD

**Issue by sarahesteves** [MatthewHerbst/react-to-print#409]
Hi. I'm using the pageStyle prop to set my document size and it's working just fine on chrome, but I'm not getting the same result on firefox. What should I do to resize the pdf document on firefox?

This is how I'm using the pageStyle prop:
`pageStyle="@page { size: 1754px 1240px; margin: 0px } @media print {html, body {height: 99%}}"`

Thanks.

**Comment by sarahesteves** [comment]
Hi, @MatthewHerbst. Would you have any ideia about how I should proceed?

**Comment by MatthewHerbst** [comment]
Hey, sorry for not responding sooner. Does the solution at the bottom of this thread work for you by chance? https://github.com/gregnb/react-to-print/issues/240

**Comment by MatthewHerbst** [comment]
I'm not sure what would be specific to Firefox to cause your current code not to work. I do know browsers treat `pageSize` very differently unfortunately

**Comment by jonrh** [comment]
I ran into this issue as well trying to achieve landscape orientation. From what I can tell the CSS `@page size` descriptor is not supported in Firefox nor Safari:

- https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size
- https://caniuse.com/mdn-css_at-rules_page_size

Seems to be supported in Chrome and Edge among other browsers. So I do not think it is an issue caused by this library.

**Comment by MatthewHerbst** [comment]
I hadn't even considered `@page size` not being supported across all browsers, thanks for checking that @jonrh!

**Comment by sarahesteves** [comment]
Hi, @jonrh ! Have you found any workaround?

**Comment by sarahesteves** [comment]
> Hey, sorry for not responding sooner. Does the solution at the bottom of this thread work for you by chance? #240

unfortunately not =/

**Comment by jonrh** [comment]
> Hi, @jonrh ! Have you found any workaround?

Unfortunately not. I found one [potential hack](https://stackoverflow.com/a/16596262), rotate the content by 90° in CSS: `transform: rotate(-90deg);`. It might work if you only need to print but the content will be all wrong if saved as a PDF.

Due to the inconsistent print behaviour of browsers my next steps will probably be to look into generating PDFs on the server side instead. Perhaps with LaTeX. Or something that gives more fine grained control.

**Comment by MatthewHerbst** [comment]
Firefox does not support the `size` property inside of `@page` currently 😢 https://caniuse.com/css-paged-media
