### ISSUE TITLE
react-to-print does not wait for videos to load

### ISSUE THREAD

**Issue by Tian94** [MatthewHerbst/react-to-print#439]
Hi there

I'm using react-to-print to print a page which has some video elements on it. At the moment it loads the video component but doesn't wait for the thumbnail of the video to load.

I've tried to use `onBeforePrint` to wait until the `loadeddata` events of the videos have all run but it doesn't seem to work. I'm guessing it won't be possible without updating the `react-to-print` source code to wait for the video thumbnails to load similar to what's being done for images here? https://github.com/gregnb/react-to-print/blob/master/src/index.tsx#L320

Please let me know if I'm correct or if there is a way of waiting for videos to load.

Thank you!

**Comment by MatthewHerbst** [comment]
Hello. Thanks for reporting the issue. Have you tried with `onBeforeGetContent`? But you are correct we don't do anything special currently, and we probably should! Could you possibly make a small demo on codesandbox showing the issue so I can debug properly for your use-case? Thank you

**Comment by Tian94** [comment]
Thank you @MatthewHerbst . I've just tried `onBeforeGetContent` now and it didn't work either :(.

Here's a sandbox where I've placed a video in the components to print. The `FunctionalComponentWithHook` example waits for the `onLoadedData` event of the video.

https://codesandbox.io/s/react-to-print-forked-402y0

Thanks for looking into this.

**Comment by MatthewHerbst** [comment]
Hello. I hope you are having a good holiday. I've had time to experiment with this and have been having a very hard time getting the browser to wait to print until the video is loaded in a state that the print dialog will take the currently loaded frame. However, I have seen that even existing versions of the library will properly show `video` elements that have a [`poster`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-poster) attribute. I'm going to keep working on just being able to load the first frame of the video, but I feel like the poster is actually the better solution because the first video frame might not be what you actually want to show as the placeholder.

**Comment by MatthewHerbst** [comment]
The fix for this is published in `v2.14.3`. Please let me know if you run into any additional issues, and thank you for reporting! Happy holidays
