### ISSUE TITLE
Getting empty pdf pages some time randomly, seeing mostly first time when we login and click on print

### ISSUE THREAD

**Issue by nagsky1** [MatthewHerbst/react-to-print#445]
![image](https://user-images.githubusercontent.com/22009172/146139279-6508976b-ede8-48bf-b6e0-652f7378a628.png)
Hi all, i am getting above image issue, seeing mostly first time when we login and click on print. we even added condition like when api success and data is there then only that component should load, i added consoles in print component, in that print component data is printing in consoles but not printing in print component. 

Can anyone please suggest me what to do to fix this issue?

**Comment by MatthewHerbst** [comment]
Hello. Happy to help. Could you please possibly post the code you are using? Hard to debug an image

**Comment by nagsky1** [comment]
@MatthewHerbst 

Yes added gist link for actual code and attached mock response object in gist comment.

https://gist.github.com/nagsky1/498bb3fd504630ccae880e6e0fb68f68

**Comment by nagsky1** [comment]
> @MatthewHerbst
> 
> Yes added gist link for actual code and attached mock response object in gist comment.
> 
> https://gist.github.com/nagsky1/498bb3fd504630ccae880e6e0fb68f68

@MatthewHerbst   @Arcturus5404  @devuxer @cmckni3  Can you please suggest what went wrong in this code

**Comment by MatthewHerbst** [comment]
I don't see anything obviously wrong. Would love to be able to test it somewhere. Is the website currently live somewhere, or is it possible for you to make a minimum reproduction on codesandbox?

**Comment by nagsky1** [comment]
@MatthewHerbst Okay, Thanks for your reply. I will add code in codesandbox and update you in couple of hours,

**Comment by nagsky1** [comment]
@MatthewHerbst 
https://codesandbox.io/s/late-surf-o7c7g?file=/src/App.js

Added codesandbox link, added minimum code to print the code. functionality working with this code. this the copy of original code but just added static mock object.

**Comment by MatthewHerbst** [comment]
I've taken a look and I can't replicate the problem locally. I wonder if it has to do with all the image loading, it's possible that the browser doesn't cache the images because of the `display: none` which would cause the print dialog to have to wait for all the images to load before it can display. My guess is the browser has a time-out on that window and if content doesn't load in a certain amount of time it just drops it. I don't believe this is a specific issue with `react-to-print`. Are you able to inline the images by chance, or find someway to have the browser load them even while the content is hidden?

**Comment by almacenero** [comment]
This is the component  code https://codesandbox.io/s/new?file=/src/App.js

**Comment by MatthewHerbst** [comment]
I'm 100% sure that component prints without issue since you can copy it into the official `react-to-print` codesandbox and there is no problem. There's clearly something going on with a component or style somewhere. I really can't be of much help if you can't share the code, you'll have to debug on your own. Please let me know once you figure out what the issue is.

**Comment by adergham** [comment]
I have exactly the same issue on a project of mine and after investigation, I think I have found the cause.
React-to-print creates an iframe and loads the content to print into this iframe.
Once the content is fully loaded, the print function of the browser should be called. However, the print function may be called before all the fonts are fully loaded.
It depends on the latency, the browser cache and the size of the content to print.

**Comment by MatthewHerbst** [comment]
@adergham have you tried passing the fonts taking a long time to load `fonts` prop? It's not perfect and needs a redesign on how it works, and ideally should be automatic, but it was made with the intention of allowing you to tell `react-to-print` a set of fonts to pre-load before printing
