### ISSUE TITLE
Blank printout with and without `copyStyles`

### ISSUE THREAD

**Issue by fosteman** [MatthewHerbst/react-to-print#455]
Having the same issue as in #410

Exactly the same setup as of @lizarragadev

```tsx
export const ComponentToPrint = forwardRef((props, ref) => {
  return (
    <Box
      ref={ref}
      sx={{
        backgroundImage: `url(${example})`,
        height: 400,
        // width: 400,
        objectFit: "cover",
        backgroundSize: "contain",
        backgroundRepeat: "no-repeat",
        // background-position: 50% 50%;
      }}
    >
      <Typography variant={"d3"}>Plastic free packaging</Typography>
    </Box>
  );
});

...

const print = useReactToPrint({
    copyStyles: true,
    content: () => {
      return ref.current;
    },
  });
```

The `Typography` is copied over if `copyStyles: false`, but the background image just does not get rendered anyway. 
<img width="1221" alt="Screen Shot 2022-01-10 at 7 10 18 AM" src="https://user-images.githubusercontent.com/32850517/148763947-408d8e3e-4baa-4c5e-a6a1-af15a1f4582f.png">

Any suggestions ?

**Comment by MatthewHerbst** [comment]
Hello. Without seeing your code I can't really help debug. Could do ideally make a working codesandbox please? Thank you

**Comment by fosteman** [comment]
@MatthewHerbst , as I said, the setup is identical to the OP of #410 . 

Component I'm printing is this:
```tsx
export const ComponentToPrint = forwardRef((props, ref) => {
  return (
    <Box
      ref={ref}
      sx={{
        backgroundImage: `url(${example})`,
        height: 400,
        // width: 400,
        objectFit: "cover",
        backgroundSize: "contain",
        backgroundRepeat: "no-repeat",
        // background-position: 50% 50%;
      }}
    >
      <Typography variant={"d3"}>Plastic free packaging</Typography>
    </Box>
  );
});

```

That's the parent component:
```tsx
export default observer((props: any) => {
  const ref = useRef(null);

  const print = useReactToPrint({
    documentTitle: "AwesomeFileName",
    copyStyles: false,
    content: () => {
      return ref.current;
    },
  });

  return (<Box>

            <ComponentToPrint ref={ref} />

              <Button
                onClick={print}
              >
                <Print /> Print
              </Button>
            </Box>
  );
});

```

**Comment by MatthewHerbst** [comment]
I will reiterate that simply looking at the abstract code is not enough to help me help you debug. For example, the implementation of `Box` is likely very important here.

**Comment by fosteman** [comment]
Material UI v5 components.

The problem is fixed by using standard html components: div, p, img, etc. Mui components are not printed.

**Comment by MatthewHerbst** [comment]
> The problem is fixed by using standard html components: div, p, img, etc. Mui components are not printed.

Sounds like the problem is clearly with MUI then, not `react-to-print`.

I'm not an expert in MUI, but my guess is that they have an `@media print` query in their code that's screwing things up. Are you able to search your site's CSS to see if that is indeed in the code?

Looking at MUI code, docs, examples, here are a few links that seem relevant:

- How to specify your own `@media print` on the `Box` component [docs](https://github.com/mui-org/material-ui/blob/15c64b3a2b32e71259451475545509806b886db2/docs/src/pages/system/basics/basics.md#superset-of-css)
- MUI setting the body background to white during prints [code](https://github.com/mui-org/material-ui/blob/fdda0411f524275a6191008f8e9db4bd22b5dbd1/packages/mui-material/src/CssBaseline/CssBaseline.js#L21)
- MUI example of how to show/hide `Box` components for printing [code](https://github.com/mui-org/material-ui/blob/ca07b0bd18c1f75d8c0de3d5715474afbb004b32/docs/src/pages/system/display/Print.js)
- MUI `displayPriont` prop [docs1](https://github.com/mui-org/material-ui/blob/ca07b0bd18c1f75d8c0de3d5715474afbb004b32/docs/src/pages/system/display/Print.js) [docs2](https://github.com/mui-org/material-ui/blob/fd7168f4b755009fb3db4a79bffc04a6febf3635/docs/src/pages/system/the-sx-prop/the-sx-prop.md#display)
- MUI `displayPrint` in `Box` props [code](https://github.com/mui-org/material-ui/blob/5042ea5beac9f779312a0bab7e29ffc2f870edf8/packages/mui-system/src/Box/Box.d.ts#L32)
- MUI properties table, including `display` and `displayPrint` [docs](https://github.com/mui-org/material-ui/blob/1b05b0beb11e64b746e9cb74193b5c671ff817ae/docs/src/pages/system/properties/properties.md#L19)
