### ISSUE TITLE
Can you use EDF's (Export Default Functions), with 

### ISSUE THREAD

**Issue by PersonGuyGit** [MatthewHerbst/react-to-print#456]
I am trying to implement ReactToPrint, to print out the contents of the export default function ToDoList (Which returns a map of the Todo cards from another class).
```jsx
export default function ToDoList({ todos, toggleTodo }) {
  return todos.map((todo) => {
    return <Todo key={todo.id} toggleTodo={toggleTodo} todo={todo} />;
  });
}
```
The ReactToPrint library seems to prefer if you use a Class Component, or a functional component like below.
```jsx
export const ComponentToPrint = React.forwardRef((props, ref) => {
  return (
    <div ref={ref}>
      <h2>Grocery List Contents</h2>
    </div> 
  );
});
```
What is the best way that I could use the ToDoList Default Function, with ReactToPrint?

Thank you for your time.

**Comment by MatthewHerbst** [comment]
Hello. Two problems. First, as a functional component you must wrap it using `React.forwardRef` since functional component by default do not accept a `ref` props. Then, a second issue is that you need a root element for the `ref` to attach to, and a component that just returns an array doesn't have that. I think it will work if you do this:
```jsx
const ToDoList = React.forwardRef(({ todos, toggleTodo }, ref) => {
  const todos = todos.map((todo) => {
    return <Todo key={todo.id} toggleTodo={toggleTodo} todo={todo} />;
  });

  return <div ref={ref}>{todos}</div>;
});

export default ToDoList;
```
