### ISSUE TITLE
save component to a pdf file

### ISSUE THREAD

**Issue by lidaof** [MatthewHerbst/react-to-print#46]
Hi,

Can we save component to a pdf file instead of open print dialog?
Thanks.

**Comment by MatthewHerbst** [comment]
Directly saving a file is very, very different than just opening the print prompt. It's arguably the work for a totally different library since the logic would be almost completely different. Also, most browsers let you save a PDF from the print prompt.

https://stackoverflow.com/questions/44989119/generating-a-pdf-file-from-react-components

**Comment by gregnb** [comment]
Agree with @MatthewHerbst this is something out of scope for this library and as pointed out you can most of the time by default save to PDF
