### ISSUE TITLE
Is there a way to print an embed (PDF) element?

### ISSUE THREAD

**Issue by MarcosCunhaLima** [MatthewHerbst/react-to-print#467]
Hi

I'm using version 2.12.4 (btw, it works flawlessly, congratulations).
Now, I have an <embed> element (with a PDF on it) which I couldn't make it print (it always shows an empty screen when I visualize to print).
Is it a limitation or I'm doing something wrong? 

The test I made so far was changing the <embed> element with a simple <div> test </div>. It shows at screen and prints ok. When I change it to the real <embed>, it shows the PDF on screen but prints nothing.

**Comment by MatthewHerbst** [comment]
Hello, thanks for the kind words. My guess is the PDF is loading asynchronously, and `react-to-print` doesn't know when the loading has finished. Could you share a code example please? A working codesandbox showing the minimally reproduced problem would be ideal.

**Comment by MarcosCunhaLima** [comment]
Hi Matthew
So, you think there is no restriction using ReactToPrint with an embed element? If so, I will try to work it out, it could be what you said but I have had this problem with printing in general (when the print depends on external resources) and worked it out.

**Comment by MatthewHerbst** [comment]
`react-to-print` does its best to wait for external resources, but doesn't know about non-standard types. For example, it knows to wait for `<img>` tags to load. If you could please share some code I might be able to suggest potential solutions.

**Comment by MarcosCunhaLima** [comment]
Hi Matthew

So, I've made an example (two, btw). On both, I have a PDF data (ready, in a file) and I will utilize it to simulate a PDF printing.
On both, we call a PDFViewer component from the App.js:

```jsx
import PDFViewer from "./Pdf";
import React, { useRef } from "react";

import { pdfData } from "./pdfData";
import { useReactToPrint } from "react-to-print";

function App() {
  const componentRef = useRef();
  const handlePrint = useReactToPrint({
    content: () => componentRef.current
  });

  return (
    <div className="App">
      
      <div ref={componentRef}>
        <PDFViewer data={pdfData} />
      </div>
     
      <button onClick={handlePrint}>Print this out!</button>
    </div>
  );
}

export default App;
```



The first uses just `<embed>`  element.

```jsx
import React from "react";

export default function PDFViewer({ data }) {
  if (!data) {
    return null;
  }

  return (
   
    <div style={{ width: "793", height: "1122" }}>
      <embed
        src={`data:application/pdf;base64,${data}`}
        width="793"
        height="1122"
        type="application/pdf"
      />
    </div>
  );
}
```

The second uses a library `react-pdf`:

```jsx
import React from "react";

import { Document, Page, pdfjs } from "react-pdf";

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

export default function PDFViewer({ data }) {
  if (!data) {
    return null;
  }

  return (
    <Document file={`data:application/pdf;base64,${data}`}>
       <Document file={url}>
       <Page pageNumber={1} wrap={false} />
     </Document>
    
  );
}
```

Just to recap, my first choice was to use `react-pdf` in order to view it. But, when I print, in chrome, it works well but in Firefox or Safari, it always print two pages (I have to squeeze the width to a minimum in order to have it print in one page).

So, I decided to use `<embed>` element in the viewer. 

In chrome, it complains 'Printing failed because the `contentWindow` of the print iframe did not load'. If you run it in codesandbox, it shows nothing but in a standalone project, it shows this error.

In Firefox, sometimes it prints correctly, sometimes it prints nothing and warns that pdf.js is not fully loaded when you close the window.

Could you give me some advice?
The project in CodeSandBox is [PDFZViewer](https://codesandbox.io/s/headless-https-do4zqs?file=/src/Pdf.jsx)

**Comment by MatthewHerbst** [comment]
There seems to be a lot of browser inconsistency here. Taking your Codesandbox (using the full-page version: https://do4zqs.csb.app/), even just using the default cmd/ctrl+p each browser has a different result:

- Chrome: prints a single page
- Safari: prints two pages but reduces to a single page if you turn off header/footer
- Firefox: prints two pages even with header/footer off

My guess is there's something a bit more nuanced going on here. It makes sense that `react-pdf` prints at least, because under the hood they use a `canvas` to actually display the PDF, and we have tests that ensure `react-to-print` works with the `canvas` element.

Playing with the `height` prop on the `Page` component from `react-pdf`, it seems once the height goes above 698 (measured in pixels) FireFox will always print a second page. For now, if you can resize the content in your PDF to look nice with a max height of 698px that's probably the best solution to get it working for you.

The `embed` element is not one that `react-to-print` knows to wait for. Codesandbox seems to not even allow the `embed` version to load because its page is sandboxed, and `embed` can have security concerns if used improperly. Even without us waiting for `embed` I don't know why you get that error using it, I'll look into that since we certainly shouldn't be failing on it, and I believe it's simple enough to check if it's done loading using the `onload` event.

**Comment by MarcosCunhaLima** [comment]
Hi Matthew

Yes, using `react-pdf` and changing height to maximum 698px, it prints just one page in firefox. The problem is it's very unreliable (I've tested several times and after a try, it starts printing 2 pages without no reason - you have to shrink it to 600px to print again one page). This happens only in firefox.
So, after four days without any decisive improvement, I decided to use `print-js` library to print raw pdf and it worked flawlessly in every browser. 

I changed the project a little bit in order to verify if the printing is a PDF. If so, it just runs:
`printJS({printable: pdf, type: 'pdf', base64: true})`
where pdf is a variable filled with an encoded64 pdf array of char.

I think it's not `react-to-print` to don't print correctly as it prints everything else wonderfully but I had to do something. Just to recap:
If I use `react-pdf` library to create a component and use `react-ot-print` to print it, it prints 2 pages using Firefox.
If I use `embed` element, `react-to-print` and browser complains that `pdf.js` is not loaded properly.
