### ISSUE TITLE
Is it possible to create a PDF automatically without opening a print window?

### ISSUE THREAD

**Issue by konstantinkrumin** [MatthewHerbst/react-to-print#484]
Hello,

On my web app I have 2 buttons: ```Print``` and ```Share```. 

I set up ```react-to-print``` library to work with ```Print``` button, it opens up a print overlay with contents of the page and I'm able to either print it directly or save as PDF as it is supposed to be. However, on ```Share``` button click I would like to open an overlay inside the app from which user would be able to send a PDF with contents of the page to emails or other messengers, therefore I would need to have a PDF document generated automatically, when user clicks on Share button, that would be attached to emails or messages sent out. 

Is there a way to set it up with react-to-print library?

**Comment by MatthewHerbst** [comment]
Hello. `react-to-print` does not actually generate a PDF. We just generate HTML which the browser (Chrome, Firefox, etc) then converts to a PDF. If you want to create a PDF on the client you would need to use a PDF generation library such as [`@react-pdf/renderer`](https://github.com/diegomura/react-pdf). Hope that helps!

**Comment by konstantinkrumin** [comment]
@MatthewHerbst Thank you!

**Comment by konstantinkrumin** [comment]
@MatthewHerbst is there actually a way to hook in the hook to get a generated HTML without opening this print window and just simply reuse the HTML generated with such library as [html2canvas](https://github.com/niklasvh/html2canvas) to create a screenshot of it and then input it to the React-pdf?

**Comment by MatthewHerbst** [comment]
Yes! You can pass a `print` prop to `react-to-print` which receives the generated iframe, and can return a Promise:

```tsx
const handlePrint = useReactToPrint({
  ...,
  print: async (printIframe: HTMLIframeElement) => {
    // Do whatever you want here, including asynchronous work
    await generatePDFFunction(printIframe);
  },
});
```

**Comment by konstantinkrumin** [comment]
@MatthewHerbst Thanks! I tried this one and I was able to extract HTML from this iFrame, however the styling went completely off. I noticed that react-to-print library is passing that additional styling that I added for printing inside ```<style><style />``` tags, so the library I'm using next to generate PDF file is getting messy layout (which I guess makes sense since those tags are only for print)

```tsx
const handleShare = useReactToPrint({
		content: () => componentRef.current,
		documentTitle: `${documentTitle}.pdf`,
		copyStyles: true,
		print: async (printIframe: HTMLIFrameElement) => {
			const document = printIframe.contentDocument;
			if (document) {
				const html = document.getElementsByTagName('html')[0];
				console.log(html);
				await html2pdf().from(html).save();
			}
		}
	});
```

**Comment by MatthewHerbst** [comment]
Yeah, since you aren't actually printing the `@media print` queries won't work. You should be able to pass in any styles you need though to make it look nice. You can override the default styles `react-to-print` sets by passing the `pageStyle`, though by default [all we really do](https://github.com/gregnb/react-to-print/blob/2925f9e5a7222adf7f68d7df857b62d6b5169872/src/index.tsx#L29) is change the margin a bit and hide the URL

**Comment by JoelRaglant** [comment]
> @MatthewHerbst Thanks! I tried this one and I was able to extract HTML from this iFrame, however the styling went completely off. I noticed that react-to-print library is passing that additional styling that I added for printing inside `<style><style />` tags, so the library I'm using next to generate PDF file is getting messy layout (which I guess makes sense since those tags are only for print)
> 
> ```
> const handleShare = useReactToPrint({
> 		content: () => componentRef.current,
> 		documentTitle: `${documentTitle}.pdf`,
> 		copyStyles: true,
> 		print: async (printIframe: HTMLIFrameElement) => {
> 			const document = printIframe.contentDocument;
> 			if (document) {
> 				const html = document.getElementsByTagName('html')[0];
> 				console.log(html);
> 				await html2pdf().from(html).save();
> 			}
> 		}
> 	});
> ```

Thank you for this. I tried the same. But onAfterPrint function is not getting triggered once the pdf got saved. Any idea?

**Comment by MatthewHerbst** [comment]
@JoelRaglant that's a bug! We forgot to call it when a custom `print` function is used. Will get a fixed up version published tonight, sorry about that

**Comment by MatthewHerbst** [comment]
@JoelRaglant should be fixed in `v2.14.7`, please let me know if you run into additional issues

**Comment by JoelRaglant** [comment]
Thank you @MatthewHerbst !! It works fine now.

**Comment by eseTunde** [comment]
> > @MatthewHerbst Thanks! I tried this one and I was able to extract HTML from this iFrame, however the styling went completely off. I noticed that react-to-print library is passing that additional styling that I added for printing inside `<style><style />` tags, so the library I'm using next to generate PDF file is getting messy layout (which I guess makes sense since those tags are only for print)
> > ```
> > const handleShare = useReactToPrint({
> > 		content: () => componentRef.current,
> > 		documentTitle: `${documentTitle}.pdf`,
> > 		copyStyles: true,
> > 		print: async (printIframe: HTMLIFrameElement) => {
> > 			const document = printIframe.contentDocument;
> > 			if (document) {
> > 				const html = document.getElementsByTagName('html')[0];
> > 				console.log(html);
> > 				await html2pdf().from(html).save();
> > 			}
> > 		}
> > 	});
> > ```
> 
> Thank you for this. I tried the same. But onAfterPrint function is not getting triggered once the pdf got saved. Any idea?

Hello, I'm trying to do this same thing. Was this all you used to create pdf download to local folder on the click of a button?

**Comment by guilhermevieira010797** [comment]
where the h*** this 'html2pdf' comes from? on typescript/nextjs

**Comment by eseTunde** [comment]
> where the h*** this 'html2pdf' comes from? on typescript/nextjs

It's an NPM package.

However it didn't quite give me the expected result, so I ended up achieveing that using react-to-print and another NPM package - js-html2pdf.

Here's what my final code looked like:

```js
const handleDownload = useReactToPrint({
  onPrintError: (error) => console.log(error),
  content: () => ref.current,
  removeAfterPrint: true,
  print: async (printIframe) => {
    const document = printIframe.contentDocument;
    if (document) {
      const html = document.getElementsByTagName("html")[0];
      console.log(html);
      const exporter = new Html2Pdf(html);
      await exporter.getPdf(true);
    }
  },
});
```
Hope it helps.

**Comment by rkushkuley** [comment]
Html2PDF is returning it as an image inside the pdf. Are there any libraries that return it at the same quality as the preview does after you download it?

**Comment by germanmedinasl** [comment]
@eseTunde Hello, I'm using yours:
```js
const handleDownload = useReactToPrint({
    onPrintError: (error) => console.log(error),
    content: () => componentRef.current,
    removeAfterPrint: true,
    print: async (printIframe) => {
      const document = printIframe.contentDocument;
      if (document) {
        const html = document.getElementsByTagName("html")[0];
        console.log(html);
        const exporter = new Html2Pdf(html,{filename:"Nota Simple.pdf"});
        exporter.getPdf(true);
      }
    },
  });
```
The console log shows the html code tags, however, the pdf is generated empty. I don't know what else to do at this point. Any suggestion would be welcome.

**Comment by Fiewor** [comment]
> Html2PDF is returning it as an image inside the pdf. Are there any libraries that return it at the same quality as the preview does after you download it?

Sorry, I don't know of any at the moment.

**Comment by Fiewor** [comment]
> 

Try adding an _await_ to `exporter.getPdf(true);` so it becomes `await exporter.getPdf(true);`

**Comment by germanmedinasl** [comment]
@Fiewor Thank you for your answer. Actually that gives me the exact same result. I'm really desperate, I don't understand why it does not work. 
Edit: I have tried just calling an element showing on screen and it displays on the PDF, but maybe as the print dialog is not shown yet, there is nothing to "put" in the PDF. Could it be the case? @eseTunde you could be of great help here.

**Comment by MatthewHerbst** [comment]
If you are passing a custom `print` prop/function then the print dialog will only show if you at some point call `window.print` within there, though I don't think that's what you actually want to do. The `printIframe` passed to that function should contain all of the DOM that needs to be printed. Have you verified that the `printIframe` has the content you expect? If it does then there is likely a problem with your usage of `Html2Pdf`

**Comment by germanmedinasl** [comment]
@MatthewHerbst Unable to get what I was triying, I did a workaround and conditionally renderer elements on screen to print correctly as it was only putting on the pdf file the elements shown on screen. I'm not that good of a programmer so you can put here that meme of the dog in the lab: "I have no idea what I'm doing".

**Comment by MatthewHerbst** [comment]
> it was only putting on the pdf file the elements shown on screen

Does the library you are using to display the list/elements do [virtual rendering](https://www.patterns.dev/posts/virtual-lists/)? If so, that would explain the issue: `react-to-print` doesn't know about virtual rendered items since they aren't in the DOM, so we aren't able to capture them. Ideally you would use `onBeforeGetContent` to modify the DOM with all the elements you want to print.

**Comment by nalinwijayasinghe** [comment]
Hello

Can anyone help me to open the PDF on the browser instead of the print window please? I am a new one to this.

**Comment by MatthewHerbst** [comment]
> Hello
> 
> Can anyone help me to open the PDF on the browser instead of the print window please? I am a new one to this.

Hello, you would need to use a PDF generation library. `react-to-print` is not capable of generating PDFs on its own, we rely on the browser's print preview to do that for us

**Comment by 15tanvir** [comment]
HiAny solution regarding,  pdf download...?

**Comment by 15tanvir** [comment]
Hii
Any solution for downloading pdf directly? Or any library for downloading pdf directly.

**Comment by MatthewHerbst** [comment]
`react-to-print` does not support direct downloading of a PDF. There are many libraries that allow you to create PDFs in the client. You can use those on their own, and/or combine `react-to-print` with one by using a custom `print` function and passing the `HTMLIframeElement` that we supply to it to the PDF generator:

```tsx
const handlePrint = useReactToPrint({
  //...,
  print: (iframe: HTMLIframeElement) => {
    // the `iframe` contains the content you want printed. Now pass it to an HTML->PDF generator
  }
})
```

**Comment by edgar-carrillo** [comment]
> @Fiewor Thank you for your answer. Actually that gives me the exact same result. I'm really desperate, I don't understand why it does not work. Edit: I have tried just calling an element showing on screen and it displays on the PDF, but maybe as the print dialog is not shown yet, there is nothing to "put" in the PDF. Could it be the case? @eseTunde you could be of great help here.

I also ran into this, the only thing was that it would only download the component I wanted as a pdf once, if that, and the rest of the time it would download blank pdfs.

If you look at the code below, if you log variable `html`  it logs the `html` elements along with the `head`, `body`, and everything else nested within `<html>`.

```javascript
const handleDownload = useReactToPrint({
    onPrintError: (error) => console.log(error),
    content: () => componentRef.current,
    removeAfterPrint: true,
    print: async (printIframe) => {
      const document = printIframe.contentDocument;
      if (document) {
        const html = document.getElementsByTagName("html")[0];
        console.log(html);
        const exporter = new Html2Pdf(html,{filename:"Nota Simple.pdf"});
        exporter.getPdf(true);
      }
    },
  });
```

Instead of returning the `html` element, I targeted the exact component I wanted downloaded as a pdf.

Making this `const html = document.getElementsByTagName("html")[0];`

Become this `const html = document.getElementById("element-to-download-as-pdf");`

Now it downloads the component I want 100% of the time.

```javascript
const handleDownload = useReactToPrint({
    onPrintError: (error) => console.log(error),
    content: () => componentRef.current,
    removeAfterPrint: true,
    print: async (printIframe) => {
      const document = printIframe.contentDocument;
      if (document) {
        const html = document.getElementById("element-to-download-as-pdf");
        console.log(html);
        const exporter = new Html2Pdf(html,{filename:"Nota Simple.pdf"});
        exporter.getPdf(true);
      }
    },
  });
```

**Comment by ErtyDess** [comment]
@edgar-carrillo nice, it worked for a while and then it work no  more, because it says 
_"To print a functional component ensure it is wrapped with `React.forwardRef`, and ensure the forwarded ref is used. See the README for an example: https://github.com/gregnb/react-to-print#examples"_

can you show me the component you print please? thank you!

it's very strange because i have a class component not a functional one.

this is the function where i call:
```tsx
        import React, { useRef } from 'react';
        import { useReactToPrint } from 'react-to-print';
        import Button from '@mui/material/Button';
        import { useStateContext } from "../../../../contexts/ContextProvider";
        import ComponentToPrint from "./ComponentToPrint";
        import Html2Pdf from 'js-html2pdf';

        export default function CreatePDF(props) {
          const { primary } = useStateContext();
          let componentRef = useRef();

          const handleDownload = useReactToPrint({
            onPrintError: (error) => console.log(error),
            content: () => componentRef.current,
            removeAfterPrint: true,
            print: async (printIframe) => {
              const document = printIframe.contentDocument;
              if (document) {
                const html = document.getElementById("element-to-download-as-pdf");
                console.log(html);
                const exporter = new Html2Pdf(html,{filename:"Nota Simple.pdf"});
                exporter.getPdf(true);
              }
            },
          });

          return (
            <>
              <Button variant='contained' style={{ backgroundColor: primary, marginLeft: '1%' }} onClick={handleDownload}>PDF</Button>
              <div style={{ display: "none" }}>
                <ComponentToPrint ref={(el) => (componentRef = el)} genVoucher={props.genVoucher} />
              </div>
            </>
          );
```
this is my component that is printed: 
```tsx
      import React from 'react';

      export default class ComponentToPrint extends React.Component {
        render() {
          const { genVoucher } = this.props
          return (
            <div style={{ padding: '100px', textAlign: 'center' }} id='element-to-download-as-pdf'>
              <h3>Username: {genVoucher.username}</h3>
              <h3>Password: {genVoucher.password}</h3>
              <h3>Validity: {genVoucher.validity / 60} minutes</h3>
              <h3>Expiry time: {new Date(genVoucher.expirytime * 1000).toLocaleDateString()} {new Date(genVoucher.expirytime * 1000).toLocaleTimeString() }</h3>
              <h3>Voucher group: {genVoucher.vouchergroup}</h3>
            </div>
          );
        }
      }
```

**Comment by johnwojtek** [comment]
> Html2PDF is returning it as an image inside the pdf. Are there any libraries that return it at the same quality as the preview does after you download it?

just like jspdf，but it needs draw the content by yourself

**Comment by walidromeo** [comment]
im using electronJs any one can help me ?

**Comment by vikramsamak** [comment]
```jsx
const handlePrint = useReactToPrint({
    content: () => printComponent.current,
    documentTitle: 'doc.pdf',
    copyStyles: true,
    print: async (printIframe) => {
        const document = printIframe.contentDocument;
	if (document) {
	    const html = document.getElementsByTagName('html')[0];
	    get_PDF_in_base64(html)
	}
    }
});
	
export const get_PDF_in_base64 = async (htmldoc) => {
    if (htmldoc) {
        const canvas = await html2canvas(htmldoc);
        const pdf = new jsPDF({
            format: "a4",
            unit: "mm",
        });
        pdf.addImage(
            canvas.toDataURL('image/jpeg'),
            'JPEG',
            0,
            0,
            pdf.internal.pageSize.getWidth(),
            pdf.internal.pageSize.getHeight()
        );
        const pdfBase64 = pdf.output('dataurlstring');
        console.log(pdfBase64);
    }
}
```

Use html2canvas and jspdf ...

**Comment by alamenai** [comment]
> > where the h*** this 'html2pdf' comes from? on typescript/nextjs
> 
> It's an NPM package.
> 
> However it didn't quite give me the expected result, so I ended up achieveing that using react-to-print and another NPM package - js-html2pdf.
> 
> Here's what my final code looked like:
> 
> ```js
> const handleDownload = useReactToPrint({
>   onPrintError: (error) => console.log(error),
>   content: () => ref.current,
>   removeAfterPrint: true,
>   print: async (printIframe) => {
>     const document = printIframe.contentDocument;
>     if (document) {
>       const html = document.getElementsByTagName("html")[0];
>       console.log(html);
>       const exporter = new Html2Pdf(html);
>       await exporter.getPdf(true);
>     }
>   },
> });
> ```
> 
> Hope it helps.

But html2pdf has not types ( Typescript ) !

**Comment by alamenai** [comment]
> ```js
> const handlePrint = useReactToPrint({
>     content: () => printComponent.current,
>     documentTitle: 'doc.pdf',
>     copyStyles: true,
>     print: async (printIframe) => {
>         const document = printIframe.contentDocument;
> 	if (document) {
> 	    const html = document.getElementsByTagName('html')[0];
> 	    get_PDF_in_base64(html)
> 	}
>     }
> });
> 	
> export const get_PDF_in_base64 = async (htmldoc) => {
>     if (htmldoc) {
>         const canvas = await html2canvas(htmldoc);
>         const pdf = new jsPDF({
>             format: "a4",
>             unit: "mm",
>         });
>         pdf.addImage(
>             canvas.toDataURL('image/jpeg'),
>             'JPEG',
>             0,
>             0,
>             pdf.internal.pageSize.getWidth(),
>             pdf.internal.pageSize.getHeight()
>         );
>         const pdfBase64 = pdf.output('dataurlstring');
>         console.log(pdfBase64);
>     }
> }
> ```
> 
> Use html2canvas and jspdf ...

I'm getting blank page though the HTML content is available:

```

  const download = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: "doc.pdf",
    copyStyles: true,
    print: async (printIframe) => {
      const document = printIframe.contentDocument
      if (document) {
        const html = document.getElementById(elementID as string)
        getPDFInBase64(html as HTMLElement)
      }
    },
  })

  const getPDFInBase64 = async (htmldoc: HTMLElement) => {
    if (htmldoc) {
      const canvas = await html2canvas(htmldoc)

      const pdf = new jsPDF({
        format: "a4",
        unit: "mm",
      })
      pdf.addImage(
        canvas.toDataURL("image/jpeg"),
        "JPEG",
        0,
        0,
        pdf.internal.pageSize.getWidth(),
        pdf.internal.pageSize.getHeight()
      )

      pdf.html(htmldoc).then(() => {
        pdf.save()
      })

      // const pdfBase64 = pdf.output("dataurlstring")
      // pdf.save()
    }

```

![image](https://github.com/gregnb/react-to-print/assets/20143684/8c38f622-7144-4ee3-a855-dcf16cda7719)

![image](https://github.com/gregnb/react-to-print/assets/20143684/a3392657-5001-436c-a0a5-e0f74093fb5c)

**Comment by yaswanthTechouts** [comment]
your mom gay

**Comment by Tsandesh** [comment]
yes it is possible to create pdf without opening. a print window but the problem that i am facing is that 
when the public images are getting cors error when trying to convert the image into blob

**Comment by MatthewHerbst** [comment]
@Tsandesh that sounds like a configuration issue with your site/server, but if you think it's an issue with `react-to-print` specifically please make a new issue for it, I haven't heard of that particular problem before but we have added nonce support in the past for other security related issues, but there's not much we can do to my knowledge for CORS specific issues since `react-to-print` runs on the same domain as your website.

**Comment by AriLaurin** [comment]
> > @Fiewor Thank you for your answer. Actually that gives me the exact same result. I'm really desperate, I don't understand why it does not work. Edit: I have tried just calling an element showing on screen and it displays on the PDF, but maybe as the print dialog is not shown yet, there is nothing to "put" in the PDF. Could it be the case? @eseTunde you could be of great help here.
> 
> I also ran into this, the only thing was that it would only download the component I wanted as a pdf once, if that, and the rest of the time it would download blank pdfs.
> 
> If you look at the code below, if you log variable `html` it logs the `html` elements along with the `head`, `body`, and everything else nested within `<html>`.
> 
> ```js
> const handleDownload = useReactToPrint({
>     onPrintError: (error) => console.log(error),
>     content: () => componentRef.current,
>     removeAfterPrint: true,
>     print: async (printIframe) => {
>       const document = printIframe.contentDocument;
>       if (document) {
>         const html = document.getElementsByTagName("html")[0];
>         console.log(html);
>         const exporter = new Html2Pdf(html,{filename:"Nota Simple.pdf"});
>         exporter.getPdf(true);
>       }
>     },
>   });
> ```
> 
> Instead of returning the `html` element, I targeted the exact component I wanted downloaded as a pdf.
> 
> Making this `const html = document.getElementsByTagName("html")[0];`
> 
> Become this `const html = document.getElementById("element-to-download-as-pdf");`
> 
> Now it downloads the component I want 100% of the time.
> 
> ```js
> const handleDownload = useReactToPrint({
>     onPrintError: (error) => console.log(error),
>     content: () => componentRef.current,
>     removeAfterPrint: true,
>     print: async (printIframe) => {
>       const document = printIframe.contentDocument;
>       if (document) {
>         const html = document.getElementById("element-to-download-as-pdf");
>         console.log(html);
>         const exporter = new Html2Pdf(html,{filename:"Nota Simple.pdf"});
>         exporter.getPdf(true);
>       }
>     },
>   });
> ```

Does this solution take account for screen resolution? I have a problem of where the end result ends up incredibly zoomed in if a user downloads the PDF on mobile

**Comment by Dillpickleschmidt** [comment]
Just wanted to post my findings here before I moved onto spending my time in better ways.
This is my attempt at generating a pdf WITHOUT using tools like html2canvas which convert everything to an image before generating a pdf, meaning I'll be able to infinitely zoom without loss of detail. I believe it's a step in the right direction if other developers want to use this as a starting point and make it better, but for most people, I'd not recommend doing this (at least in the way I've figured out).

I got pdf generation and downloading via a single button press working (sorta) in a way that DOESN'T use canvas or create an image to lower the quality. The issue is that the styling doesn't properly carry over. I'm sure someone else could pick up from here and make it work and add further improvements but I've decided it's not worth my time and I'll just try html2canvas + jsPDF (or something similar).
This setup is using NextJs 15 + TailwindCSS + ShadCn with react-to-print v3 beta. This is done in a component marked "use client" so there's no advanced server-side code going on.

I'm using 3 tools:
1. [react-to-print](https://github.com/MatthewHerbst/react-to-print) (for html styling for pdfs)
2. [react-pdf](https://github.com/diegomura/react-pdf) but specifically [this](https://github.com/diegomura/react-pdf/issues/2756#issuecomment-2163155727) build of it (currently needed for React 19 support). (for actually generating pdfs)
3. [react-pdf-html](https://github.com/danomatic/react-pdf-html) (for converting html code from react-to-print to a format that react-pdf understands)

One thing I don't think people realize at first is that all this tool (react-to-print) does is make HTML from your component with some minor styling changes that appear nice in print view. It's only 1 step in the process of actually creating a pdf.

React-to-print creates the HTML, react-pdf-html converts it to a format react-pdf likes better, and react-pdf actually generates the pdf.

Here's my code:
```tsx
"use client"

import { useState, useEffect } from "react"
import {
  PDFDownloadLink,
  Document,
  Page,
} from "@alexandernanberg/react-pdf-renderer"
import { PiFilePdf } from "react-icons/pi"
import { useReactToPrint } from "react-to-print"
import Html from "react-pdf-html"

type PrintButtonProps = {
  contentRef: React.RefObject<HTMLDivElement>
}

function MyDocument({ htmlString }: { htmlString: string }) {
  return (
    <Document>
      <Page size="A4">{<Html>{htmlString}</Html>}</Page>
    </Document>
  )
}

export default function PrintButton({ contentRef }: PrintButtonProps) {
  const [htmlContent, setHtmlContent] = useState<string | null>(null)

  const handlePrint = useReactToPrint({
    contentRef: contentRef,
    print: async (printIframe: HTMLIFrameElement) => {
      if (printIframe.contentDocument) {
        setHtmlContent(printIframe.contentDocument.body.innerHTML)
        console.log("Prepared", printIframe.contentDocument.body.innerHTML)
      }
    },
  })

  useEffect(() => {
    if (contentRef.current) {
      handlePrint()
    }
  }, [contentRef, handlePrint])

  return (
    <div className="fixed right-12 top-3">
      {htmlContent && (
        <PDFDownloadLink
          document={<MyDocument htmlString={htmlContent} />}
          fileName="test.pdf"
        >
          <PiFilePdf size={26} className="opacity-25" />
        </PDFDownloadLink>
      )}
    </div>
  )
}
```

That's why I wrap it with the <HTML> tag provided by react-pdf-html—it converts it to that structure of Document, Page, View, etc.
That's this line:
`<Page size="A4">{<Html>{htmlString}</Html>}</Page>`

That SHOULD be it, but there's another issue. I'm using an experimental build of react-pdf, and it's actually a literal different package "@alexandernanberg/react-pdf-renderer" instead of "@react-pdf/renderer". That means the react-pdf-html library itself is pointing to the wrong dependencies and it will give you an error. So follow the error path it tells you (node-modules/react-pdf-html/dist/esm/[filename])
You have to change the imports from "@react-pdf/renderer" to "@alexandernanberg/react-pdf-renderer" and save.
I think there's 3 or 4 files I changed until the error messages went away.

Yay, you're done.

By now, you should have a pdf that generates on your button press (just assign the ref to the element you want to print and pass it to your print button component, as per standard react-to-print setup) and you'll have a very ugly pdf document that technically has all of your text. Horray.

Note that with NextJs there are some errors in the server-side console and the build times have all increased. I'm assuming that's because it's trying to use client-only logic at first with react-pdf as mentioned in [this](https://www.youtube.com/watch?v=HhLa-D0SXlI) video. I haven't bothered trying to fix it since I'm moving on because of the reasons listed below.

The issue is that most (if not all) of my styling doesn't carry over. 
I've got all these warnings too:
![image](https://github.com/user-attachments/assets/2f873bbd-7fed-4b8d-8af2-e3aa39ab4ab4)

I'll also have to import a unique .ttf custom font file for every font style and another file for every weight for every custom font I use. Right now, I'm using Asian (Japanese) characters in my component which are converted into pure gibberish, maybe that will be fixed if I import a font meant for those characters (like my Noto Sans JP font).

Here's the before and after:
![image](https://github.com/user-attachments/assets/ba4afaa1-d4be-42b2-9614-1ada08025232)

![image](https://github.com/user-attachments/assets/8cfe18d6-808b-40b1-bf2e-1e21de3824dd)

As you can see, it's pretty butchered. All the basic HTML IS there (even the lists which are apparently hard to convert [supposedly flexboxes work too]). Maybe the styling will work better without TailwindCSS, idk. If someone wants to develop another tool to make these tools interplay better, go for it. But for anyone else, just stick with something like html2canvas and jsPDF.
Or, if someone has found a better solution, please let me know.

**Comment by MatthewHerbst** [comment]
Thanks for the writeup @Dillpickleschmidt, really interesting!

**Comment by jt6677** [comment]
@Dillpickleschmidt  Thx for the extensive write-up. I tried all the method mentioned on this page and still have a lot of problem exporting tailwind components as PDF.

**Comment by alamenai** [comment]
@jt6677 , could you add more details about the issues you are facing?

**Comment by jt6677** [comment]
@alamenai
-generate as pdf  
![Snipaste_2024-07-18_20-46-53](https://github.com/user-attachments/assets/18d8e1be-19cc-45ec-9df0-52b87ef577ac)
vs
-print as pdf
![Snipaste_2024-07-18_20-49-14](https://github.com/user-attachments/assets/9c3e834a-79ff-43ad-aa03-aac823c64eaa)

**Comment by jt6677** [comment]
@Dillpickleschmidt  I had some success turning component into svg using satori, encode it as dataURL and use it as Svg in react-pdf/render .    At this point, I might as well turn components as pngs.  PDF just  does not have much support for costumed  svg.

**Comment by jt6677** [comment]
or directly to pdf . https://og-playground.vercel.app/

**Comment by alamenai** [comment]
@jt6677 , how did you handle multi pages ?

**Comment by jt6677** [comment]
@alamenai
```ts
import PDFDocument from 'pdfkit/js/pdfkit.standalone'
async function createPDF() {
  const doc = new PDFDocument({
    compress: false,
    size: 'A4',
  })

 const pngUrl = await componentToPNG(TrainCardRender, ctaVariants, 595, 842)
  if (pngUrl) {
    const imageBuffer = await fetch(pngUrl).then((res) => res.arrayBuffer())
    doc.addPage().image(imageBuffer, 0, 100, { width: 595, height: 842 })
  }

  const stream = doc.pipe(blobStream())
  return new Promise<string>((resolve) => {
    stream.on('finish', () => {
      const blob = stream.toBlob('application/pdf')
      const url = URL.createObjectURL(blob)
      resolve(url)
    })
    doc.end()
  })
}
```
You just `doc.addPage()`. I tried all the lib combo, satori +pdfkit gave me the best result with tailwind support. 

![Snipaste_2024-08-20_20-09-40](https://github.com/user-attachments/assets/36fb01e6-46c1-4285-bc12-0713a992aea1)

**Comment by vikramsamak** [comment]
You can also try this microservice developed by me to convert html into pdf 

https://github.com/vikramsamak/html-to-pdf-microservice


https://html-to-pdf-microservice.onrender.com/

**Comment by Ridafatima17** [comment]
I have HTML content that is very long, sometimes over 50 pages, and occasionally even over 300 pages or more. I want to generate a PDF from this content and allow users to download it without displaying a preview in Angular and also I don't want to interrupt its workflow. Is it possible to achieve this without using a backend

**Comment by MatthewHerbst** [comment]
> I have HTML content that is very long, sometimes over 50 pages, and occasionally even over 300 pages or more. I want to generate a PDF from this content and allow users to download it without displaying a preview in Angular and also I don't want to interrupt its workflow. Is it possible to achieve this without using a backend

Hi @Ridafatima17 it is possible, you need to find a JavaScript package that can turn HTML elements into PDF (this would be what `generateAndSavePDF` in the example below does). Then you can use the `print` function to override the default behavior and get access to the print iframe element:

```tsx
const handlePrint = useReactToPrint({
  ...,
  print: async (printIframe: HTMLIframeElement) => {
    // Do whatever you want here, including asynchronous work
    await generateAndSavePDF(printIframe);
  },
});
```

**Comment by jt6677** [comment]
@Ridafatima17 I recommend you use pdf js libs like PDFkit to turn content into pdf.  They have a lot more methods and actually print content as text instead of as image.  Render 300 pages of content as image and print as pdf format will be painfully slow.

**Comment by sanirurajapaksha** [comment]
Seems like none of the above mentioned packages are able to generate a pdf with text selection, without just embedding an image in a pdf. Might have to move on to a backend solution with a bit of puppeteer.

**Comment by ghost** [comment]
> PDFkit

How did you use pdfkit in react?
