### ISSUE TITLE
Unable to render in IE11 using React 15

### ISSUE THREAD

**Issue by davegw** [MatthewHerbst/react-to-print#49]
Hi there,

Thanks for the library, very useful! 

While doing some browser testing, I was unable to render the react-to-print component in IE11. I saw there was a similar issue (#41) that appeared to be resolved in 2.0.0-alpha-3 (the version I'm using). I am using react 15 in my project (package specifies react ^16.2), but I don't see anything specific in the code that would require use of react 16. Copying the code into my codebase as opposed to importing from the node package, fixes the problem, but just posting in case others have run into this issue.

**Comment by brittonjg** [comment]
I may have run into the same issue as @davegw. If it helps, I can see the following entry reported in Sentry ```Object doesn't support property or method 'includes'```.

I am using React `16.5.2` and `2.0.0-alpha-3` of react-to-print.

Really appreciate your work, let me know if you need any further information.

Edit.

It looks like the issue is when the UserAgent is checked for whether IE 11 is being used or not here https://github.com/gregnb/react-to-print/blob/master/src/index.js#L95

Seems like includes is another thing not supported in IE 11 - https://caniuse.com/#search=includes

**Comment by gregnb** [comment]
react-to-print@2.0.0-alpha-4 should solve this thanks to @MatthewHerbst
