### ISSUE TITLE
Hyperlinks using react-to-print 

### ISSUE THREAD

**Issue by maximesenger** [MatthewHerbst/react-to-print#507]
Hello,
I am trying to add hyperlinks in the component that I am printing. I would like to be able to click on them directly in the PDF but I can't find any information about that online.

Is that possible using your package ?
If not directly, do you know if there is a "hacky" way to do it ?

Thanks a lot for your time !

**Comment by MatthewHerbst** [comment]
Hello. It's important to note that `react-to-print` does not generate PDFs. We simply generate an `iframe` that has the contents you want to print, and then by calling `window.print` we give it to the browser. Each browser decides on its own how to handle that call, which is why printing can sometimes be a little different in different browsers. Most modern browsers will convert the `iframe` into PDF, though how they do that is not related to `react-to-print`.

Most PDF handlers (including the ones built into Chrome, Firefox, and Safari) will respect `<a>` tags, so as long as you put your links into them that should work. I have heard of issues with Adobe Acrobat not always working with them. Unfortunately it's not something we have control over.

Have you encountered a link that a PDF reader won't support?

**Comment by maximesenger** [comment]
Hello,
Thank you for the answer. I have tried using firefox and chromium to 'generate' the PDF and both tranform my `<a>` tags in `<span>` on every links.

I have also tried firefox, chromium and acrobate reader to open the PDF file, same result.

**Comment by MatthewHerbst** [comment]
Can you make a codesandbox or similar where I can see the code and test it?

**Comment by maximesenger** [comment]
Sure : https://codesandbox.io/s/serene-fermi-wqb0ci

As you can see if you 'inspect' the PDF, the `a` tag is transformed in a `span`.

**Comment by maximesenger** [comment]
Oh I found out !
By changing the 'destination' field from `microsoft print to PDF` to `save as PDF` I can now click on the links.

Sorry that I have bothered you, and once again thank you for your help.

**Comment by MatthewHerbst** [comment]
No problem, glad you got it figured out!
