### ISSUE TITLE
Silent print

### ISSUE THREAD

**Issue by majid-IR-QAZ** [MatthewHerbst/react-to-print#513]
Is there any solution to print without open dialog box?

**Comment by MatthewHerbst** [comment]
Hello. There is not unfortunately, since we call [`window.print`](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) under the hood and after that each browser takes control, and there is no way to override it. You could generate a PDF locally and then download it without a dialog box popping up, but that would require using some additional libraries. Does that make sense?
