### ISSUE TITLE
CSS variable set in `useEffect` hook not applying

### ISSUE THREAD

**Issue by midhunlanware** [MatthewHerbst/react-to-print#551]
CSS variable styles not loading

**Comment by MatthewHerbst** [comment]
Hello. Could you please share your code? Ideally you could share a [Codesandbox](https://codesandbox.io/s/rzdhd) that replicates your problem. Thanks!

**Comment by midhunlanware** [comment]
Please find the code on following link [https://codesandbox.io/s/loving-tristan-d6mu6b?file=/src/App.js](https://codesandbox.io/s/loving-tristan-d6mu6b?file=/src/App.js)

**Comment by MatthewHerbst** [comment]
Interesting. I've never seen a var set like that, but it certainly is valid JS/React and so we should support it. My guess is we're not properly reading the `document.documentElement.root.style`. I'll try and look into this tonight, thanks for reporting

**Comment by MatthewHerbst** [comment]
Apologies for the delayed response. The issue seems to be because you are setting the style on the document root, which in the CodeSandbox case is an `iframe` that probably isn't behaving as you might expect. If you move the style to the App root, it works as expected: https://codesandbox.io/s/vigorous-wildflower-wt7j7r
