### ISSUE TITLE
Position fixed elements are printing in each page

### ISSUE THREAD

**Issue by PraveenVerma17** [MatthewHerbst/react-to-print#576]
There seems to be an issue with library when I print react component and any html element have position fixed then library is putting that fixed element in each page.

**Comment by MatthewHerbst** [comment]
Hello. Thanks for writing in. Any chance you can make a [CodeSandbox](https://codesandbox.io/s/rzdhd) replicating the issue?

**Comment by PraveenVerma17** [comment]
@MatthewHerbst  here is a codesandbox , Tab menu is a fixed item and after print its showing on all pages instead of first page alone. 

if i make this sticky and adjust some styling , we can see correctly example AppBar. 

[https://codesandbox.io/s/lucid-glitter-fyqysq](https://codesandbox.io/s/lucid-glitter-fyqysq)

**Comment by MatthewHerbst** [comment]
Thanks for the reproduction, that makes the issue much clearer.

I think this is actually a browser issue, and not an issue with `react-to-print`. If you use ctrl+p to print the page normally, not using `react-to-print`, you can see the same issue.

Thinking about it, what the browser is doing does make sense here. The HTML/CSS is saying "this item should always be visible in this spot" and that's what it is doing during the print. I'm not sure I fully agree with that decision, but it's not unreasonable, they had to chose something.

In terms of a solution for you, I think the semantically correct thing to do would be to make the list itself scrollable, rather than having to scroll the whole page. That way you wouldn't need to specify the `position: fixed` and it would work as intended. Here is how I would do it with your code: https://codesandbox.io/s/nice-dawn-u9576s I make the table itself scrollable when not printing, and when printing I set the height to 100% to ensure we get all of the content. Does that work for you?

**Comment by PraveenVerma17** [comment]
Thanks for your information. Not sure why all browsers print fixed item in all pages.
