### ISSUE TITLE
how to print using ctrl+p?

### ISSUE THREAD

**Issue by shibila22** [MatthewHerbst/react-to-print#582]
I am using ReactToPrint for printing ,when button is clicked it is working. 
How to print when  `ctrl + p`  is used?

**Comment by MatthewHerbst** [comment]
Hello. Unfortunately we are not able to override the behavior of `ctrl + p` since that is built-into the browsers. You should be able to use `@media print` queries to make your entire page print the way you'd like

**Comment by nightvisi0n** [comment]
Hi @shibila22,

in order to print using a shortcut like <kbd>ctrl</kbd> + <kbd>p</kbd> you can install a [keydown event listener](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event) like this:  

```typescript
// const print = useReactToPrint([...])

window.addEventListener("keydown", (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === "p") {
        e.preventDefault();
        print();
    }
});
```

In order to override the browsers default behaviour you can call `e.preventDefault()` on the event (like shown in the example).

Hope that answers your question!

**Comment by rahul-mallick-15** [comment]
I'm trying to print specific components of my app using [react-to-print][1] library. I'm trying to override the event of pressing `ctrl+p` for printing by using `event.preventDefault()` and it's working for the first time that is when the app renders, on ctrl+p the required components are getting printed but after this the second time I click ctrl+p is not getting caught inside my `handleKeyDown` function, instead the browser default of printing the entire page is happening.<br>
```tsx
import React, { useCallback, useEffect, useRef } from "react";
import { useReactToPrint } from "react-to-print";

const Example = () => {
  const componentRef = useRef();
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  });

  const handleKeyDown = useCallback(
    (event) => {
      console.log("keydown");
      if (event.ctrlKey && event.key === "p") {
        event.preventDefault();
        handlePrint();
      }
    },
    [handlePrint]
  );

  useEffect(() => {
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [handleKeyDown]);

  return (
    <div>
      <div ref={componentRef}>
        <div>Div 1</div>
        <div>Div 2</div>
        <div>Div 3</div>
      </div>
      <div>Div not printed</div>
      <button onClick={handlePrint}>Print this out!</button>
    </div>
  );
};
export default Example;

```
The ctrl+p gives the desired result the first time after every re-render but on further tries its not working. I'm assuming the issue to be with the `keyDown` event not getting caught after causing the print for the first time.
How can I get it to work properly so that ctrl+p prints the desired output ?
**Update**
What happened was when the print dialogue opened, the focus from the app was somehow lost(not sure) until I manually clicked on the screen/app component and ctrl+p worked as desired.
```tsx
const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    onAfterPrint: () => {
      document.activeElement.blur();
      componentRef.current.focus();
    },
  });
  ```
Just modifying the handlePrint function and taking the focus back on the component worked.

  [1]: https://www.npmjs.com/package/react-to-print

**Comment by MatthewHerbst** [comment]
Thanks for the details @rahul-mallick-15! I'll see about adding a link to this thread to the README so others can see it if they want
