### ISSUE TITLE
How to give A5 page printing option along with default A4 page?

### ISSUE THREAD

**Issue by shibilainfoskies** [MatthewHerbst/react-to-print#611]

**Comment by MatthewHerbst** [comment]
Hello. `react-to-print` unfortunately has no control over what is shown in the Print Preview Dialog, as there is no general browser print API available. The best you can do is to hint to the browser what you want to happen. So for example, if you want the hint to the browser that it should print using A5 instead of A4, you could do this:

```css
@media print {
  @page {
    size: A5;
  }
}
```

Note that this is just a hint, and different browsers may or may not respect it. I recommend reading more about this in our [README section](https://github.com/gregnb/react-to-print#set-the-page-size).

Going to close the issue for now, but please feel free to respond with questions and I will do my best to answer them
