### ISSUE TITLE
[security] potential attack vectors

### ISSUE THREAD

**Issue by mosesnagar** [MatthewHerbst/react-to-print#632]
hi :) 

We're using this library to print a dashboard built with react components as pdf to help our customers send it to their customers. As part of development and releasing it globally, we thought about security aspects. 
In case of malicious code inside a component, is the printing process safe? 

It's hard to think about it but let say we have a component called Dashboard. 
an attacker changed the code, using devtools, and added some js script or changed the code in useEffect or any other code injecting options. 

Or, the attacker add a malicious image to the DOM - does the malicious code will also apply after printing?

What are our options here?

**Comment by MatthewHerbst** [comment]
Hello, thanks for thinking about keeping users safe!

`react-to-print` does not add any security concerns to your website. We do not execute any 3rd party JavaScript, so the only code we interact with is whatever is already on your website. The way this library works: we take the ref you give us, find the DOM node that it corresponds to, and then copy/paste that DOM node, plus CSS, into an `iframe`. This means that, during printing, no React code will run unless _you_ specify a side-effect in the `onBeforePrint` or `onBeforeGetContent` callbacks. Further, because we execute within an `iframe` any code that is part of the DOM node is sandboxed to that `iframe`, and cannot modify the original page.

I hope that explanation is helpful, I'm happy to explain anything more if you'd like.
