### ISSUE TITLE
save or cancel button

### ISSUE THREAD

**Issue by dztzAdmin** [MatthewHerbst/react-to-print#663]
Hello, is it possible for the onAfterPrint function to provide a parameter to determine if the save or cancel button was clicked? Or is there any other way for me to know if the save or cancel button was clicked?

**Comment by MatthewHerbst** [comment]
Hello. There is no browser standard that I'm aware of around this unfortunately, I wish there was :( That's why `onAfterPrint` is so generic: all we know is that the print preview modal closed, we don't know what the user did with it. If you only care about one specific browser there might be some things you could do with an extension to detect this, not sure. Wish we could be more helpful here.

**Comment by dztzAdmin** [comment]
> Hello. There is no browser standard that I'm aware of around this unfortunately, I wish there was :( That's why `onAfterPrint` is so generic: all we know is that the print preview modal closed, we don't know what the user did with it. If you only care about one specific browser there might be some things you could do with an extension to detect this, not sure. Wish we could be more helpful here.

Okay, I understand now 😔. Thank you for your quick reply.
