### ISSUE TITLE
Why does it render different content when in im browsing in mobile

### ISSUE THREAD

**Issue by LeighDaillan** [MatthewHerbst/react-to-print#703]

**Comment by MatthewHerbst** [comment]
Hello. Could you please add some details to your question? But the likely answer is because the website you are printing from has different styles when you are on mobile.

**Comment by LeighDaillan** [comment]
Yup that's what i thought also im using this library to save the PDF also to print but when im browsing my webpage in my phone it print the webpage not the jsx that i set to pdf

**Comment by Maxnikit** [comment]
I have same issue with google chrome.

**Comment by nxtvoid** [comment]
> Yup that's what i thought also im using this library to save the PDF also to print but when im browsing my webpage in my phone it print the webpage not the jsx that i set to pdf

I have the same problem, but when I use Safari this behaviour does not happen.

**Comment by MatthewHerbst** [comment]
I believe this issue is a duplicate of https://github.com/MatthewHerbst/react-to-print/issues/187 have never gotten to the bottom of this one unfortunately. Still looking for solutions, but it may be an upstream browser issue - printing is weird enough on desktop, mobile browsers do all sorts of things. Will post updates in the other thread if I find anything new here
