### ISSUE TITLE
`contentRef` option and a optional-content param passed to its callback

### ISSUE THREAD

**Issue by Ben-CA** [MatthewHerbst/react-to-print#758]
I'm getting a warning message in my Chrome console:

"react-to-print" received a `contentRef` option and a optional-content param passed to its callback. The `contentRef` option will be ignored.

It seems to work 100%, but I'm wondering why it's giving me this warning, and how I can prevent that?

Example use with React 18:

```jsx
const printSectionRef = useRef(null);

const printSummary = useReactToPrint({
  contentRef: printSectionRef,
});

...

<div ref={printSectionRef}>
        Testing
</div>
```

**Comment by MatthewHerbst** [comment]
Hey! How are you using the `printSummary` function? The warning likely means you are passing a parameter into it when it doesn't expect to get one (because you have `contentRef` specified). We support a form of "lazy loading" the content where you don't need to specify `contentRef` and can load the content yourself later. See an example here https://github.com/MatthewHerbst/react-to-print/blob/master/examples/LazyContent/index.tsx

**Comment by Ben-CA** [comment]
Wow Matthew - thanks for the super quick response! That helped me see what I was doing wrong.

I had it like this:
`<IconButton onClick={printSummary}>`

And I've changed it to like this:
`<IconButton onClick={() => printSummary()}>`

And now I don't get the error.

**Comment by MatthewHerbst** [comment]
Great! Please let us know if you run into any other issues
